//! Backend-tagged compiled-kernel artifact.

use alloc::borrow::Cow;
use alloc::string::String;
use alloc::vec::Vec;
use serde::{Deserialize, Serialize};

use crate::dim::Dim3;

/// Identifies which backend produced (and can load) a `KernelArtifact`.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BackendId {
    /// NVIDIA CUDA (PTX).
    Cuda = 1,
    /// Vulkan compute (SPIR-V).
    Vulkan = 2,
}

impl BackendId {
    /// File-name-friendly suffix.
    pub const fn suffix(self) -> &'static str {
        match self {
            BackendId::Cuda => "ptx",
            BackendId::Vulkan => "spv",
        }
    }

    /// Uppercase env-var-friendly tag.
    pub const fn env_tag(self) -> &'static str {
        match self {
            BackendId::Cuda => "PTX",
            BackendId::Vulkan => "SPV",
        }
    }
}

/// Backend-specific target metadata embedded in an artifact.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TargetInfo {
    /// CUDA target with stream-multiprocessor capability.
    Cuda {
        /// SM major version (e.g. 8 for sm_80).
        sm_major: u8,
        /// SM minor version (e.g. 0 for sm_80).
        sm_minor: u8,
    },
    /// SPIR-V target version.
    Spirv {
        /// SPIR-V major (e.g. 1).
        major: u8,
        /// SPIR-V minor (e.g. 6).
        minor: u8,
    },
}

/// Backend-specific minimum capability requirements for a kernel.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum BackendCaps {
    /// CUDA minimum SM.
    Cuda {
        /// Minimum SM major.
        min_sm_major: u8,
        /// Minimum SM minor.
        min_sm_minor: u8,
    },
    /// SPIR-V required extensions and feature bits (post-SP1).
    Spirv {
        /// Capability bit set (placeholder; expanded in SP1).
        bits: u64,
    },
}

/// Coarse argument-kind tag carried in the manifest. Fine-grained
/// type-checking happens inside the host stub generated by the
/// `#[kernel]` macro (Plan 2). For Plan 1, only the kinds the
/// `vector_add` example uses are necessary.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ArgKind {
    /// `&Buffer<f32>` / `&mut Buffer<f32>`.
    BufferF32,
    /// `&Buffer<Complex32>` (32-bit complex; landed in Plan 3).
    BufferComplex32,
    /// `u32` scalar.
    ScalarU32,
    /// `i32` scalar.
    ScalarI32,
}

/// One entry per `#[kernel]`-tagged function in the source crate.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct KernelMeta {
    /// Stable mangled name used to look up the kernel inside the loaded module.
    pub mangled_name: String,
    /// Ordered argument kinds.
    pub arg_kinds: Vec<ArgKind>,
    /// Static shared-memory bytes the kernel declares.
    pub shared_memory_bytes: u32,
    /// Optional launcher hint.
    pub recommended_block: Option<Dim3>,
    /// Minimum backend caps required at load time.
    pub required_caps: BackendCaps,
}

/// Compiled-kernel container.
#[derive(Clone, Debug)]
pub struct KernelArtifact {
    /// Which backend produced this artifact.
    pub backend: BackendId,
    /// Target architecture / SPIR-V version.
    pub target: TargetInfo,
    /// Compiled blob: PTX bytes or SPIR-V words.
    pub blob: Cow<'static, [u8]>,
    /// One `KernelMeta` per kernel in the blob.
    pub manifest: Vec<KernelMeta>,
}
